config/routes.rb
Donar::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  root 'application#index'
  get '/about', to: 'application#about'
  get '/faq', to: 'application#faq'
  get '/tips', to: 'application#tips'

  # Users Routes

  resources :users do
    member do
      get :edit_password
      patch :update_password
    end
  end

  # End Users Routes

  # Organizations Routes

  resources :organizations do

    collection do
      get :list
      get :subregion_options
    end

    resources :comments, except: [:edit, :update]

    resources :campaigns do
      resources :milestones do
        member do
          get :achieve
          patch :confirm_achieved
        end
      end
      resources :contributions do
        collection do
          get :landing
          post :anonymous
        end
      end
      resources :comments, except: [:edit, :update]
    end
  end

  # End Organizations Routes

  # Campaigns Routes

  resources :campaigns do
    collection do
      get :search
      post :search
      get :landing
      get :subregion_options
    end
    member do
      post :approve
      get :configure
      post :configure_step2
      post :configure_step3

    end
  end

  resources :purchases do
    collection do
      get :success_mercadopago_callback
      get :pending_mercadopago_callback
      get :failure_mercadopago_callback
    end
  end

  # End Campaigns Routes

  # Mails Preview Routes

  mount MailPreview => 'mail_view' if Rails.env.development?

  # End Mails Preview Routes

  # Image Storage

  mount PostgresqlLoStreamer::Engine => '/user_avatar', as: 'user_avatar'
  mount PostgresqlLoStreamer::Engine => '/campaign_main_image', as: 'campaign_main_image'
  mount PostgresqlLoStreamer::Engine => '/milestone_file', as: 'milestone_file'

  # End Image Storage

end

app/models/user.rb
class User < ActiveRecord::Base
  extend UserAuthenticationHelper
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :identities
  has_and_belongs_to_many :organizations
  has_many :comments
  has_many :contributions

  mount_uploader :avatar, AvatarUploader

  def email_required?
    super && (provider.blank? || provider != 'twitter')
  end

  def password_required?
    super && provider.blank?
  end

  def update_with_password(params, *options)
    encrypted_password.blank? ? update_attributes(params, *options) : super
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  inherit_resources

  before_action :authenticate_user!

  FIELDS = [:first_name, :last_name, :email, :avatar, :password, :password_confirmation]

  def update_password
    if current_user.update_attributes(resource_params.first)
      sign_in(current_user, bypass: true)
      @user = current_user
      render :show
    else
      render :edit_password
    end
  end

  private

  def resource_params
    return [] if request.get?
    [params.require(:user).permit(FIELDS)]
  end

end

app/views/users/_form.html.slim
- if user.errors.present?
  .alert.alert-danger
    ul
      - user.errors.each do |attr, msg|
        li= msg
= form_for user, html: { class: 'form-horizontal', role: 'form' } do |f|
  .form-group
    = f.label :first_name, class: 'control-label col-sm-2'
    .col-md-4
      = f.text_field :first_name, class: 'form-control col-md-2', required: true
  .form-group
    = f.label :last_name, class: 'control-label col-sm-2'
    .col-md-4
      = f.text_field :last_name, class: 'form-control col-md-2', required: true
  .form-group
    = f.label :email, class: 'control-label col-sm-2'
    .col-md-4
      = f.text_field :email, class: 'form-control col-md-2', required: true
  .form-group
    = f.label :avatar, class: 'control-label col-sm-2'
    .col-md-4
      = f.file_field :avatar

  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit t('helpers.submit.user.done_edit_user'), class: 'btn btn-primary btn-violet'

app/views/users/edit.html.slim
legend
  = t('helpers.submit.user.edit')
= render 'form', user: current_user

app/views/users/edit_password.html.slim
- if current_user.errors.present?
  .alert.alert-danger
    ul
      - current_user.errors.each do |attr, msg|
        li= msg
= form_for current_user, url: update_password_user_path, html: { class: 'form-horizontal', role: 'form' } do |f|
  - if current_user.errors.any?
    .alert.alert-error
      = devise_error_messages!
  .form-group
    = f.label :password, class: 'control-label col-sm-2'
    .col-md-4
      = f.password_field :password, class: 'form-control col-md-2', required: true
  .form-group
    = f.label :password_confirmation, class: 'control-label col-sm-2'
    .col-md-4
      = f.password_field :password_confirmation, class: 'form-control col-md-2', required: true

  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit t('helpers.submit.user.done_edit_password'), class: 'btn btn-primary btn-violet'

app/views/users/show.html.slim
legend#profile-header
  = t('users.profile')
.col-sm-3
  - if @user.avatar.present?
      = image_tag(@user.avatar.file.url, height: 150, width: 150, class: "img-thumbnail img-profile")
  - else
      = image_tag('default_avatar.jpg', height: 150, width: 150, class: "img-thumbnail img-profile")
  a
    = link_to t('helpers.submit.user.edit'), edit_user_path(@user), class: 'btn btn-primary btn-violet btn-profile'
  a
    = link_to t('helpers.submit.user.edit_password'), edit_password_user_path(@user), class: 'btn btn-primary btn-violet btn-profile'
.row
  .col-sm-7
    .panel.profile-panel
      .panel-heading
        = User.human_attribute_name(:full_name)
      .panel-body
        = @user.full_name
    .panel.profile-panel
      .panel-heading
        .panel-title
          = User.human_attribute_name(:email)
      .panel-body
        = @user.email
    .panel.profile-panel
      .panel-heading
        = User.human_attribute_name(:created_at)
      .panel-body
        = l(@user.created_at, format: :short)
    .panel.profile-panel
      .panel-heading
        .panel-title
          = t('users.link_accounts')
      .panel-body
        - unless provider?("facebook")
          = link_to "Facebook", user_omniauth_authorize_path(:facebook), class: 'btn btn-primary btn-facebook'
        - unless provider?("google_oauth2")
          = link_to "Google", user_omniauth_authorize_path(:google_oauth2), class: 'btn btn-primary btn-google'
        - unless provider?("twitter")
          = link_to "Twitter", user_omniauth_authorize_path(:twitter), class: 'btn btn-primary btn-twitter'
.row
  legend#profile-subheader
    = t('users.organizations')
  = render '/organizations/index_table', organizations: @user.organizations.page(1).per(50)
  legend#profile-subheader
    = t('users.contributions')
  = render '/contributions/index_table', contributions: paginate_scope(@user.contributions)