config/routes.rb
Donar::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  root 'application#index'
  get '/about', to: 'application#about'
  get '/faq', to: 'application#faq'
  get '/tips', to: 'application#tips'

  # Users Routes

  resources :users do
    member do
      get :edit_password
      patch :update_password
    end
  end

  # End Users Routes

  # Organizations Routes

  resources :organizations do

    collection do
      get :list
      get :subregion_options
    end

    resources :comments, except: [:edit, :update]

    resources :campaigns do
      resources :milestones do
        member do
          get :achieve
          patch :confirm_achieved
        end
      end
      resources :contributions do
        collection do
          get :landing
          post :anonymous
        end
      end
      resources :comments, except: [:edit, :update]
    end
  end

  # End Organizations Routes

  # Campaigns Routes

  resources :campaigns do
    collection do
      get :search
      post :search
      get :landing
      get :subregion_options
    end
    member do
      post :approve
      get :configure
      post :configure_step2
      post :configure_step3

    end
  end

  resources :purchases do
    collection do
      get :success_mercadopago_callback
      get :pending_mercadopago_callback
      get :failure_mercadopago_callback
    end
  end

  # End Campaigns Routes

  # Mails Preview Routes

  mount MailPreview => 'mail_view' if Rails.env.development?

  # End Mails Preview Routes

  # Image Storage

  mount PostgresqlLoStreamer::Engine => '/user_avatar', as: 'user_avatar'
  mount PostgresqlLoStreamer::Engine => '/campaign_main_image', as: 'campaign_main_image'
  mount PostgresqlLoStreamer::Engine => '/milestone_file', as: 'milestone_file'

  # End Image Storage

end

app/views/confirmable/shared/_links.html.slim
- if controller_name != 'sessions'
  = link_to t('devise.sessions.sign_in'), new_session_path(resource_name)
  br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to t('devise.sessions.sign_in_with_provider', provider: provider.to_s.titleize),
              omniauth_authorize_path(resource_name, provider),
              class: 'btn btn-primary omniauth-button', id: "btn-#{provider.to_s}"
    br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to t('devise.registrations.sign_up'), new_registration_path(resource_name), class: 'btn btn-primary btn-blue'
  br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to t('devise.sessions.forgot_password'), new_password_path(resource_name)
  br/
  br
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to t('devise.confirmable.didnt_receive_email_confirmation'), new_confirmation_path(resource_name)
  br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to t('devise.confirmable.didnt_receive_unlock_instructions'), new_unlock_path(resource_name)
  br/