config/routes.rb
Donar::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  root 'application#index'
  get '/about', to: 'application#about'
  get '/faq', to: 'application#faq'
  get '/tips', to: 'application#tips'

  # Users Routes

  resources :users do
    member do
      get :edit_password
      patch :update_password
    end
  end

  # End Users Routes

  # Organizations Routes

  resources :organizations do

    collection do
      get :list
      get :subregion_options
    end

    resources :comments, except: [:edit, :update]

    resources :campaigns do
      resources :milestones do
        member do
          get :achieve
          patch :confirm_achieved
        end
      end
      resources :contributions do
        collection do
          get :landing
          post :anonymous
        end
      end
      resources :comments, except: [:edit, :update]
    end
  end

  # End Organizations Routes

  # Campaigns Routes

  resources :campaigns do
    collection do
      get :search
      post :search
      get :landing
      get :subregion_options
    end
    member do
      post :approve
      get :configure
      post :configure_step2
      post :configure_step3

    end
  end

  resources :purchases do
    collection do
      get :success_mercadopago_callback
      get :pending_mercadopago_callback
      get :failure_mercadopago_callback
    end
  end

  # End Campaigns Routes

  # Mails Preview Routes

  mount MailPreview => 'mail_view' if Rails.env.development?

  # End Mails Preview Routes

  # Image Storage

  mount PostgresqlLoStreamer::Engine => '/user_avatar', as: 'user_avatar'
  mount PostgresqlLoStreamer::Engine => '/campaign_main_image', as: 'campaign_main_image'
  mount PostgresqlLoStreamer::Engine => '/milestone_file', as: 'milestone_file'

  # End Image Storage

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :campaigns
  has_and_belongs_to_many :users
  has_many :comments, as: :commentable
  validates :name, :description, :country, :locality, presence: true

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  inherit_resources

  before_action :authenticate_user!, except: [:index, :show]

  FIELDS = [:name, :description, :locality, :country]

  def list
    @organizations = current_user.organizations.page(params[:page] || 1)
  end

  def subregion_options
    render partial: 'subregion_select'
  end

  def create
    create! do
      if @organization.valid?
        @organization.users << current_user
        organization_path @organization
      end
    end
  end

  def index
    index! { @organizations = @organizations.page(params[:page] || 1) }
  end

  private

  def resource_params
    return [] if request.get?
    [params.require(:organization).permit(FIELDS)]
  end

end

app/views/organizations/_form.html.slim
- if organization.errors.present?
  .alert.alert-danger
    ul
      - organization.errors.each do |attr, msg|
        li= msg
= form_for organization, html: { class: 'form-horizontal', role: 'form' } do |f|
  .form-group
    = f.label :name, class: 'control-label col-sm-2'
    .col-md-4
      = f.text_field :name, class: 'form-control col-md-2', required: true
  .form-group
    = f.label :description, class: 'control-label col-sm-2'
    .col-md-4
      = f.text_area :description, class: 'form-control col-md-2', required: true
  .form-group
    = f.label :country, class: 'control-label col-sm-2'
    .col-md-4
      = f.country_select :country, selected: 'AR',class: 'form-control', required: true
  .form-group
    = f.label :locality, class: 'control-label col-sm-2'
    .col-md-4
      #subregion
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit nil, class: 'btn btn-primary btn-violet'

app/views/organizations/_index_table.html.slim
- if organizations.empty?
  p
    = t('application.no_results')
- else
  table.table.table-bordered.table-hover
    thead
      tr
        th
          = Organization.human_attribute_name(:name)
        th
          = Organization.human_attribute_name(:description)
        th
          = Organization.human_attribute_name(:locality)
    tbody
    - organizations.each do |organization|
      tr
        td
          = link_to organization.name, organization
        td
          = organization.description
        td
          = Carmen::Country.coded(organization.country).subregions.coded(organization.locality).name
#pagination
  = paginate organizations

app/views/organizations/_subregion_select.html.slim
- parent_region = params[:parent_region]

= subregion_select(:organization, :locality, parent_region)

app/views/organizations/edit.html.slim
legend
  = t('helpers.submit.organization.edit')
= render 'form', organization: @organization

app/views/organizations/index.html.slim
legend
  = Organization.model_name.human(count: 2)
= render 'index_table', organizations: @organizations

app/views/organizations/list.html.slim
legend
  = t('users.organizations')
= render 'index_table', organizations: @organizations

app/views/organizations/new.html.slim
legend
  = t('helpers.submit.organization.new')
= render 'form', organization: @organization

app/views/organizations/show.html.slim
legend
  = Organization.model_name.human
.row
  .col-md-6
    ul.list-group
      li.list-group-item
        h4.list-group-item-heading
          = Organization.human_attribute_name(:name)
        p.list-group-item-text
          = @organization.name
      li.list-group-item
        h4.list-group-item-heading
          = Organization.human_attribute_name(:description)
        p.list-group-item-text
          = @organization.description
      li.list-group-item
        h4.list-group-item-heading
          = Organization.human_attribute_name(:country)
        p.list-group-item-text
          = Carmen::Country.coded(@organization.country).name
      li.list-group-item
        h4.list-group-item-heading
          = Organization.human_attribute_name(:locality)
        p.list-group-item-text
          = Carmen::Country.coded(@organization.country).subregions.coded(@organization.locality).name

- if policy(@organization).update?
  .row
    .col-md-6
      p
        = link_to t('helpers.submit.organization.edit'), edit_organization_path(@organization),
              class: 'btn btn-primary btn-violet'
legend
  = Campaign.model_name.human(count: 2)
= render '/campaigns/index_cards', campaigns: paginate_scope(@organization.campaigns)

- if policy(@organization).update?
  p
    = link_to t('helpers.submit.campaign.new'), new_organization_campaign_path(@organization),
              class: 'btn btn-primary btn-violet'
.row
  .col-md-12
    legend
      = Comment.model_name.human(count: 2)
    - @organization.comments.each do |comment|
      = render 'comments/comment_card', comment: comment
p
  = link_to t('helpers.submit.comment.new'), new_organization_comment_path(@organization),
            class: 'btn btn-primary btn-violet'