config/routes.rb
Donar::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  root 'application#index'
  get '/about', to: 'application#about'
  get '/faq', to: 'application#faq'
  get '/tips', to: 'application#tips'

  # Users Routes

  resources :users do
    member do
      get :edit_password
      patch :update_password
    end
  end

  # End Users Routes

  # Organizations Routes

  resources :organizations do

    collection do
      get :list
      get :subregion_options
    end

    resources :comments, except: [:edit, :update]

    resources :campaigns do
      resources :milestones do
        member do
          get :achieve
          patch :confirm_achieved
        end
      end
      resources :contributions do
        collection do
          get :landing
          post :anonymous
        end
      end
      resources :comments, except: [:edit, :update]
    end
  end

  # End Organizations Routes

  # Campaigns Routes

  resources :campaigns do
    collection do
      get :search
      post :search
      get :landing
      get :subregion_options
    end
    member do
      post :approve
      get :configure
      post :configure_step2
      post :configure_step3

    end
  end

  resources :purchases do
    collection do
      get :success_mercadopago_callback
      get :pending_mercadopago_callback
      get :failure_mercadopago_callback
    end
  end

  # End Campaigns Routes

  # Mails Preview Routes

  mount MailPreview => 'mail_view' if Rails.env.development?

  # End Mails Preview Routes

  # Image Storage

  mount PostgresqlLoStreamer::Engine => '/user_avatar', as: 'user_avatar'
  mount PostgresqlLoStreamer::Engine => '/campaign_main_image', as: 'campaign_main_image'
  mount PostgresqlLoStreamer::Engine => '/milestone_file', as: 'milestone_file'

  # End Image Storage

end

app/views/layouts/_about_us.html.slim
#about-us
  div
    .about-title
      = t('application.about.title')
    .about-subtitle
      = t('application.about.introduction.title')
    .about-text
      = t('application.about.introduction.content')
    .about-subtitle
      = t('application.about.origins.title')
    .about-text
      = t('application.about.origins.content')
    .about-subtitle
      = t('application.about.goals.title')
    .about-list
      ul
        li
          = t('application.about.goals.goal1')
        li
          = t('application.about.goals.goal2')
        li
          = t('application.about.goals.goal3')
        li
          = t('application.about.goals.goal4')
        li
          = t('application.about.goals.goal5')
    .about-sponsor
      div
        a href='http://www.forodelsectorsocial.org.ar'
          = image_tag 'logo-foro.png'
      div
        a href='http://www.itba.edu.ar'
          = image_tag 'logo-itba.png'
        a href='http://www.ourmark.com'
          = image_tag 'logo-ourmark.png'
        a href='http://www.estudiofrenesi.com.ar'
          = image_tag 'logo-frenesi.png'

app/views/layouts/_content.html.slim
.row
  #header-carousel.carousel.slide data-ride="carousel"
    ol.carousel-indicators
      li data-slide-to="0" data-target="#carousel-example-captions"
      li.active data-slide-to="1" data-target="#header-carousel"
      li data-slide-to="2" data-target="#cheader-carousel"
    .carousel-inner
      .item
        = image_tag 'first-carousel-image.jpg'
          .carousel-caption
            h3 Comedor Infantil
            p Nulla vitae elit libero, a pharetra augue mollis interdum.
      .item.active
        = image_tag 'second-carousel-image.jpg'
          .carousel-caption
            h3 Second slide label
            p Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      .item
        = image_tag 'third-carousel-image.jpg'
          .carousel-caption
            h3 Third slide label
            p Praesent commodo cursus magna, vel scelerisque nisl consectetur.
    a.left.carousel-control data-slide="prev" href="#header-carousel"
      span.glyphicon.glyphicon-chevron-left
    a.right.carousel-control data-slide="next" href="#header-carousel"
      span.glyphicon.glyphicon-chevron-right
#campaigns-title.row
  .pull-left
    = Campaign.model_name.human(count: 2)
  .pull-right
    = link_to t('application.all'), campaigns_path
#campaigns-cards
  = render 'campaigns/index_cards', campaigns: campaigns
#slogan
  p
    = t('application.why_comunidar').html_safe
#slogan-images
  .col-sm-4
    = image_tag 'facil.png'
    p
      = t('application.easy')
  .col-sm-4
    = image_tag 'vital.png'
    p
      = t('application.vital')
  .col-sm-4
    = image_tag 'transparente.png'
    p
      = t('application.transparent')

app/views/layouts/_footer.html.slim
#footer-upper
  #footer-sections.col-md-4
    div
      p
        = link_to t('application.footer.create_campaign'), landing_campaigns_path
      p
        = link_to t('application.footer.who_are_we'), about_path
      p
        = link_to t('application.footer.faq'), faq_path
      p
        = link_to t('application.footer.tips'), tips_path

  #footer-sponsors
    div
      a href='http://www.itba.edu.ar'
        = image_tag 'logo-itba.png'
      a href='http://www.ourmark.com'
        = image_tag 'logo-ourmark.png'
      a href='http://www.estudiofrenesi.com.ar'
        = image_tag 'logo-frenesi.png'
#footer-lower
  div
    p.pull-left
      = link_to t('application.footer.terms'), '#'
      = ' | '
      = link_to t('application.footer.privacy'), '#'

app/views/layouts/_header.html.slim
#brand.col-sm-4.pull-left
  = link_to root_path do
    = image_tag 'logo.png'
.col-sm-7.pull-right
  .row
    .pull-right
      = form_tag search_campaigns_path, class: 'form-inline', role: 'form' do
        .form-group
          #header-search.pull-left
            = search_field_tag 'query', nil, class: 'form-control', placeholder: t('campaigns.search')
            = image_submit_tag 'search.png'
            - if user_signed_in?
              = link_to t('devise.sessions.sign_out'), destroy_user_session_path, method: :delete,
                        class: 'btn btn-primary btn-green'
            - else
              = link_to t('devise.sessions.sign_in'), '#',
                        class: 'btn btn-primary btn-green',
                        data: { toggle: 'modal', target: '#login-modal' }

  #header-pills.row
    ul.nav.nav-pills.pull-right
      - if user_signed_in?
        li
          = link_to t('application.footer.profile'), current_user
      li
        = link_to t('application.footer.create_campaign'), landing_campaigns_path
      li
        = link_to t('application.footer.who_are_we'), about_path
= render 'layouts/login_modal'

app/views/layouts/_login_modal.html.slim
#login-modal.modal.fade.bs-example-modal-sm
  .modal-dialog
    .modal-content
      .modal-header
        h4.modal-title
          = t('devise.sessions.sign_in')
      .modal-body
        = form_for(:user, url: session_path(:user)) do |f|
          .form-group
            = f.email_field :email, autofocus: true, placeholder: t('application.email'),
                            class: 'form-control', required: true
          .form-group
            = f.password_field :password, autocomplete: 'off', class: 'form-control',
                               placeholder: t('application.password'), required: true
          .checkbox
            .pull-left
              = f.check_box :remember_me
              = f.label t('devise.sessions.remember_me')
            .pull-right
              = link_to t('devise.sessions.forgot_password'), new_password_path(:user)
          .form-group
            = f.submit t('devise.sessions.sign_in')
      .modal-footer
        .row
          .form-group
              = link_to t('devise.registrations.sign_up'), new_registration_path(:user),
                class: 'btn btn-primary omniauth-button'
        .row
          = link_to t('devise.sessions.sign_in_with_facebook'),
                    user_omniauth_authorize_path(:facebook),
                    class: 'btn btn-primary omniauth-button', id: 'btn-facebook'
        .row
          = link_to t('devise.sessions.sign_in_with_twitter'),
                    user_omniauth_authorize_path(:twitter),
                    class: 'btn btn-primary btn-violet omniauth-button', id: 'btn-twitter'
        .row
          = link_to t('devise.sessions.sign_in_with_google'),
                    user_omniauth_authorize_path(:google_oauth2),
                    class: 'btn btn-primary btn-violet omniauth-button', id: 'btn-google_oauth2'

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-inverse role="navigation" style="position: static;"
  .container-fluid
    /! Brand and toggle get grouped for better mobile display
    .navbar-header
      button.navbar-toggle data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
      = link_to "Donar", root_path, class: "navbar-brand"
    /! Collect the nav links, forms, and other content for toggling
    ul.nav.navbar-nav.pull-right
      - if user_signed_in?
        li
          = link_to t('users.profile'), current_user
        li
          = link_to t('devise.sessions.sign_out'), destroy_user_session_path, method: :delete
      - else
        li
          = link_to t('devise.sessions.sign_in'), new_user_session_path
        li
          = link_to t('devise.sessions.sign_in_with_facebook'),
            user_omniauth_authorize_path(:facebook)
        li
          = link_to t('devise.sessions.sign_in_with_google'),
            user_omniauth_authorize_path(:google_oauth2)
        li
          = link_to t('devise.sessions.sign_in_with_twitter'),
            user_omniauth_authorize_path(:twitter)

app/views/layouts/application.html.slim
doctype html
html lang = I18n.locale
  head
    title Donar
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    - if content_for?(:head)
        = yield(:head)


  body data-controller=controller.controller_path data-action=controller.action_name
    .container
      #header.row
        = render 'layouts/header'
    .container
      #content.row
        - flash.each do |name, msg|
          = content_tag :div, msg, class: flash_class(name)
        = yield
    #footer.row
      = render 'layouts/footer'

app/views/layouts/email.html.slim
| Email layout
= yield